### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pkallerm** [Akimyou/ts-whammy#34]
Hi -- 

I'm trying to figure out how to use ts-whammy with a form that uploads pictures from a folder, processes them and then shows the webm file. Any ideas? 

It's basically this: http://techslides.com/demos/image-video/create.html

Any ideas how to implement this with ts-whammy?

Philip

**Comment by Akimyou** [comment]
Yes, it can do it. I will give you an example later today.

发自我的iPhone

**Comment by pkallerm** [comment]
Thank you! Xie xie!

**Comment by Akimyou** [comment]
@pkallerm , please see this demo. https://akimyou.github.io/ts-whammy/#upload-images-to-video
