### ISSUE TITLE
Types not exported

### ISSUE THREAD

**Issue by MelleB** [Akimyou/ts-whammy#42]
Hi! The library looks great. Many thanks for your effort!
Unfortunately I can't seem to get it to work, the typescript declarations cannot be found.

## To reproduce:
1. Create an empty project and add `ts-whammy` as a dependency.
 ```
yarn add ts-whammy@1.1.0
```
2. Create an file that uses `ts-whammy`, e.g.
```ts
// test.ts
import Whammy from 'ts-whammy';
const blob = Whammy.fromImageArray([], 24)
``` 
3. Try to compile the file
```sh
yarn tsc test.ts
```

## Actual result
```
test.ts:1:20 - error TS2307: Cannot find module 'ts-whammy' or its corresponding type declarations.

1 import Whammy from 'ts-whammy';
                     ~~~~~~~~~~~

Found 1 error in test.ts
```

## Expected result
No errors

## Analysis
I think there is a publishing error to NPM. The `@types` and `libs` directories are missing when I'm installing the plugin, these directories are mentioned in `package.json`.

If I run the following commands inside my `node_modules` folder, the error disappears:
```sh
cd node_modules/ts-whammy
yarn install
yarn build:libs
cd ../..
yarn tsc test.ts
# No error
```

**Comment by Akimyou** [comment]
Will check and fix it to night 

发自我的iPhone

**Comment by Akimyou** [comment]
Thanks for the issue 

发自我的iPhone

**Comment by MelleB** [comment]
Thanks for the quick reply! 👍🙂

**Comment by Akimyou** [comment]
fixed: https://www.npmjs.com/package/ts-whammy?activeTab=explore

please use v1.1.1

Thanks.

**Comment by MelleB** [comment]
Thanks :+1:
