### ISSUE TITLE
where is the file?

### ISSUE THREAD

**Issue by higgerlynch** [Akimyou/ts-whammy#47]
where is the actual file that I can put in folder to use as a library? the equivalent of whammy.js? all i can see is random unrelated files

**Comment by Akimyou** [comment]
Please see the demo～发自我的 iPad在 2023年11月25日，20:03，higgerlynch ***@***.***> 写道：﻿
where is the actual file that I can put in folder to use as a library? the equivalent of whammy.js? all i can see is random unrelated files

**Comment by Akimyou** [comment]
Please see this demo:

- https://akimyou.github.io/ts-whammy/demo1/
- https://akimyou.github.io/ts-whammy/demo2/
