### ISSUE TITLE
It doesn't work in Safari (both iOS and MacOS), does it?

### ISSUE THREAD

**Issue by flashist** [Akimyou/ts-whammy#48]
I keep getting errors, like:
**Before toWebM Error, Image Index 0**
**Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'riff.RIFF[0]')**

In addition to that the [demo page](https://akimyou.github.io/ts-whammy/demo2/) seems to have the same problems:
![Screenshot 2024-01-03 at 15 49 14](https://github.com/Akimyou/ts-whammy/assets/15659804/c7a5f19c-3906-4be6-9e4d-878badc10196)

I wonder if there are any ways to make this lib work with Safari?

**Comment by Akimyou** [comment]
No, it only can use in chrome.
