### ISSUE TITLE
Lack of dependency

### ISSUE THREAD

**Issue by SeiyaCooper** [Akimyou/ts-whammy#49]
The `tslib` package is required in the `libs-esm/index.js` file, but it's not included in the `package.json` dependencies.

**Comment by Akimyou** [comment]
Ok, i will check

**Comment by Akimyou** [comment]
will fix today.

**Comment by SeiyaCooper** [comment]
Thanks a lot ;)

**Comment by Akimyou** [comment]
Fixed on 1.1.5
